-   use_table: true
-   center: (0.5, 0.5, 0)
    lang: a common desk lamp
    name: Lamp
    on_table: true
    path: lamp.urdf
    reward_asset_path: '13928'
    size: 0.5
    type: urdf
-   solution_path: data/generated_tasks/Lamp_13928_2023-10-05-02-12-48/task_Change_Lamp_Direction
-   joint_3: random
    set_joint_angle_object_name: Lamp
-   spatial_relationships: []
-   task_description: "The robotic arm will alter the lamp\u2019s light direction\
        \ by manipulating the lamps head"
    task_name: Change Lamp Direction
